---
- name: Install the 'Development tools' package group
  dnf:
    name: '@Development tools'
    state: present
  become: yes

- name: DNF install packages
  dnf:
    name:
    - automake
    - bash-completion
    - curl
    - fzf
    - git
    - gnupg2
    - go
    - ImageMagick
    - jq
    - kubectl
    - libpq-devel
    - libtool
    - mongodb-org
    - openssl
    - openssl-devel
    - postgresql
    - readline-devel
    - ruby
    - ShellCheck
    - which
    - yarn
    - zlib-devel
    state: present
  become: yes
